/* Generated by GitHub Actions for Pages deployment. For local testing, copy
   config.example.js to config.js and fill in your public Supabase values. */
window.TARSHID_CONFIG = window.TARSHID_CONFIG || {
  supabaseUrl: "https://wanfivxdroaqiojfgbxu.supabase.co",
  supabaseAnonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhbmZpdnhkcm9hcWlvamZnYnh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg2OTEwMjgsImV4cCI6MjA5NDI2NzAyOH0.Rmg_KK_Qc7MTCRmH2lhjkdX3kf5jm2Sbg6hJ0hDR-Cc"
};
