/* Generated by GitHub Actions for Pages deployment. For local testing, copy
   config.example.js to config.js and fill in your public Supabase values. */
window.TARSHID_CONFIG = window.TARSHID_CONFIG || {
  supabaseUrl: "",
  supabaseAnonKey: ""
};
